name = "clothing-pos-otp-worker"
main = "src/index.ts"
compatibility_date = "2026-06-23"
compatibility_flags = ["nodejs_compat"]

[vars]
GMAIL_BASE = "naddieclo@gmail.com"
FIREBASE_PROJECT_ID = "shein-pos"
FRONTEND_ORIGIN = "https://krljde.github.io"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "844d65e45b0448199035026f35f3f931"
